### ISSUE TITLE
Flytt admin-siden til profilen

### ISSUE THREAD

**Issue by olros** [tihlde/Kvark#309]
Istedenfor at admin-oversikten med linker til arrangementadmin, nyhetsadmin, osv.. skal være en egen side, hadde det vært fint å ha den inne på profilen som en egen tab på samme måte som Arrangementer, Badges, osv...

**Todo**:
- [ ] Lag en komponent i Profile, for eks `ProfileAdmin.tsx`
- [ ] Vis frem kort til de forskjellige admin-sidene basert på hvilke grupper du er med i
- [ ] Istedenfor å linke til Admin-siden i profil, bytter du til å vise Admin-taben
- [ ] Slett Admin-siden og eventuelle linker til den. Også `URLS.admin` i `URLS.js`
